### ISSUE TITLE
parse mdl faces error

### ISSUE THREAD

**Issue by ilimei** [4eb0da/war3-model#12]
```mdl
Faces 12 36 {
  Triangles {
	  {0, 1, 2},
	  {3, 4, 5},
	  {6, 7, 8},
	  {9, 10, 11},
	  {12, 13, 14},
	  {15, 16, 17},
	  {0, 18, 1},
	  {3, 19, 4},
	  {6, 20, 7},
	  {9, 21, 10},
	  {12, 22, 13},
	  {15, 23, 16},
  }
}
```
Faces reader mdl only parse one array 
at code https://github.com/4eb0da/war3-model/blob/master/mdl/parse.ts#L581
for this file should parse 12 times array

**Comment by 4eb0da** [comment]
Never saw such models, thanks
Fixed in master, would be in the next version (some day)
https://github.com/4eb0da/war3-model/commit/a0967dc4e0ba83fb7558bfe099ab59e236cb6bb9
