### ISSUE TITLE
Preview the model error

### ISSUE THREAD

**Issue by w4454962** [4eb0da/war3-model#2]
[model.zip](https://github.com/4eb0da/war3-model/files/3504630/model.zip)
This model vertex is not correct, but in war3 is normal

**Comment by 4eb0da** [comment]
Thanks! I'll try to investigate this, but some time past after the project was in active phase :)

**Comment by 4eb0da** [comment]
Fixed in version 1.1.0!
https://github.com/4eb0da/war3-model/releases/tag/v1.1.0
Examples also was updated and now contains a fix
