### ISSUE TITLE
Preview model error

### ISSUE THREAD

**Issue by 435352980** [4eb0da/war3-model#3]
[Kururu.zip](https://github.com/4eb0da/war3-model/files/3523428/Kururu.zip)
find wrong hands behavior on rendering this model

**Comment by 4eb0da** [comment]
Thank you!
I've increased MAX_NODES from 128 to 256, this model should be fine now
It also increases hardware requirements a bit, but i don't think this numbers would be an issue in 2019
Please, notice me, if something went worse then before!
https://github.com/4eb0da/war3-model/releases/tag/v1.1.1

**Comment by 435352980** [comment]
Very cool!!! Thank you very much.
and the "renderer" folder was not published to the npm package?
recently i tried to use it to preview some game models, and is there some way to work with
some models like wings on different attachments? 
look like this
![983C1C51-3782-43B0-A213-5FA8CA7ABF10](https://user-images.githubusercontent.com/35485428/63637788-87b8ed80-c6b3-11e9-93b3-466bd538152d.png)
![2DD34C5E-7F02-49FD-B6E3-43C06FC1F8C4](https://user-images.githubusercontent.com/35485428/63637787-87b8ed80-c6b3-11e9-9fa2-7465fc59d3e8.png)

I'm very sorry, because my English is not very well.

**Comment by 4eb0da** [comment]
>  and the "renderer" folder was not published to the npm package?

Oops. Fixed in 1.2.0!

> recently i tried to use it to preview some game models, and is there some way to work with
some models like wings on different attachments?

I can provide some API to work with attachments (get position / matrix), but i think combining models is outside of current project. Maybe later
