### ISSUE TITLE
NPM Missing renderer classes

### ISSUE THREAD

**Issue by bloor** [4eb0da/war3-model#6]
npm install is missing **/renderer** folder/functionality/classes ( https://prnt.sc/AL-tk1O7QGDQ )
Trying to use it in my Vue project.

**Comment by 4eb0da** [comment]
Hello!
Somehow i've missed renderer in non-browser build
Thx for pointing that! I've released a new `2.1.0` version. Check it, please, is it okay now?

**Comment by bloor** [comment]
Works like a charm.
https://prnt.sc/T9UFub305R2O
